# _config.yml

# GitHub Pages settings
title: Color Picker
description: An Angular color picker project

# GitHub Pages branch
# Set to 'main' or 'master' depending on your default branch
publish_branch: main

# Exclude these files and folders from the GitHub Pages build
exclude:
  - node_modules
  - .gitignore
  - README.md
  - LICENSE

# Angular-specific configuration
defaults:
  - scope:
      path: ""
      type: "angular"
    values:
      layout: "angular"

# Specify the folder where the built Angular app is located

# Base URL for the project
baseurl: "/color-picker"
url: "https://mruanova.github.io"

---
"$schema": "./node_modules/@angular/cli/lib/config/schema.json"
version: 1
newProjectRoot: projects
projects:
  color-picker:
    projectType: application
    schematics:
      "@schematics/angular:component":
        style: scss
    root: ''
    sourceRoot: src
    prefix: app
    architect:
      build:
        builder: "@angular-devkit/build-angular:application"
        options:
          outputPath: dist/color-picker
          index: src/index.html
          browser: src/main.ts
          polyfills:
          - zone.js
          tsConfig: tsconfig.app.json
          inlineStyleLanguage: scss
          assets:
          - src/favicon.ico
          - src/assets
          styles:
          - src/styles.scss
          scripts: []
        configurations:
          production:
            budgets:
            - type: initial
              maximumWarning: 500kb
              maximumError: 1mb
            - type: anyComponentStyle
              maximumWarning: 2kb
              maximumError: 4kb
            outputHashing: all
          development:
            optimization: false
            extractLicenses: false
            sourceMap: true
        defaultConfiguration: production
      serve:
        builder: "@angular-devkit/build-angular:dev-server"
        configurations:
          production:
            buildTarget: color-picker:build:production
          development:
            buildTarget: color-picker:build:development
        defaultConfiguration: development
      extract-i18n:
        builder: "@angular-devkit/build-angular:extract-i18n"
        options:
          buildTarget: color-picker:build
      test:
        builder: "@angular-devkit/build-angular:karma"
        options:
          polyfills:
          - zone.js
          - zone.js/testing
          tsConfig: tsconfig.spec.json
          inlineStyleLanguage: scss
          assets:
          - src/favicon.ico
          - src/assets
          styles:
          - src/styles.scss
          scripts: []
