# _config.yml

# GitHub Pages settings
title: Color Picker
description: An Angular color picker project

# GitHub Pages branch
# Set to 'main' or 'master' depending on your default branch
publish_branch: main

# Exclude these files and folders from the GitHub Pages build
exclude:
  - node_modules
  - .gitignore
  - README.md
  - LICENSE

# Angular-specific configuration
defaults:
  - scope:
      path: ""
      type: "angular"
    values:
      layout: "angular"

# Specify the folder where the built Angular app is located
include:
  - src

# Base URL for the project
baseurl: "/color-picker"
url: "https://mruanova.github.io"